# Release setup wizard — MatchCV
# Fills production .env + eas.json hints, prints remaining manual steps.
#
# Usage:
#   .\scripts\release-setup.ps1
#   .\scripts\release-setup.ps1 -RenderUrl "https://matchcv-api.onrender.com" -GitHubUser "myuser"

param(
  [string]$RenderUrl = "",
  [string]$GitHubUser = "",
  [string]$ExpoOwner = "",
  [string]$RevenueCatKey = "",
  [string]$ApiKey = "",
  [switch]$NonInteractive
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

function Prompt-Value {
  param([string]$Label, [string]$Default = "", [switch]$Secret)
  if ($NonInteractive -and $Default) { return $Default }
  $suffix = if ($Default) { " [$Default]" } else { "" }
  $raw = Read-Host "$Label$suffix"
  if ([string]::IsNullOrWhiteSpace($raw)) { return $Default }
  return $raw.Trim()
}

Write-Host "`n=== MatchCV — Release Setup ===`n" -ForegroundColor Cyan

if (-not $RenderUrl) {
  $RenderUrl = Prompt-Value "Backend URL on Render (https://matchcv-api.onrender.com)" ""
}
if (-not $GitHubUser) {
  $GitHubUser = Prompt-Value "GitHub username (for Pages privacy URL)" ""
}
if (-not $ExpoOwner) {
  $ExpoOwner = Prompt-Value "Expo account username (EXPO_OWNER)" ""
}
if (-not $RevenueCatKey) {
  $RevenueCatKey = Prompt-Value "RevenueCat Android key (goog_..., empty = skip)" ""
}
if (-not $ApiKey) {
  $ApiKey = "prod-" + [guid]::NewGuid().ToString("N").Substring(0, 24)
  Write-Host "Generated API_KEY: $ApiKey" -ForegroundColor DarkGray
}

$privacyBase = if ($GitHubUser) {
  "https://$GitHubUser.github.io/matchcv"
} else {
  "https://YOUR_GITHUB_USERNAME.github.io/matchcv"
}

# Read existing Groq key from backend/.env if present
$groqKey = ""
$backendEnvPath = Join-Path $root "backend\.env"
if (Test-Path $backendEnvPath) {
  foreach ($line in Get-Content $backendEnvPath) {
    if ($line -match "^GROQ_API_KEY=(.+)$") { $groqKey = $Matches[1]; break }
  }
}

$mobileEnv = @"
# Production — generated by release-setup.ps1 $(Get-Date -Format "yyyy-MM-dd")
EXPO_PUBLIC_API_URL=$RenderUrl
EXPO_PUBLIC_API_KEY=$ApiKey
EXPO_PUBLIC_PRIVACY_URL=$privacyBase/privacy.html
EXPO_PUBLIC_TERMS_URL=$privacyBase/terms.html
EXPO_PUBLIC_REVENUECAT_API_KEY_ANDROID=$RevenueCatKey
EXPO_PUBLIC_REVENUECAT_API_KEY_IOS=

EAS_PROJECT_ID=
EXPO_OWNER=$ExpoOwner
EAS_UPDATE_URL=
"@

$backendEnv = @"
PORT=3001
API_KEY=$ApiKey
AI_PROVIDER=groq
GROQ_API_KEY=$groqKey
AI_MODEL=llama-3.3-70b-versatile
CORS_ORIGIN=*
RATE_LIMIT_MAX=100
"@

Set-Content -Path (Join-Path $root ".env") -Value $mobileEnv -Encoding UTF8
Set-Content -Path $backendEnvPath -Value $backendEnv -Encoding UTF8

Write-Host "`nUpdated .env and backend/.env" -ForegroundColor Green

# Validate
Write-Host "`nValidating preview profile..." -ForegroundColor Yellow
node scripts/validate-production.js --profile preview
$previewOk = $LASTEXITCODE -eq 0

Write-Host "Validating production profile..." -ForegroundColor Yellow
node scripts/validate-production.js --profile production
$prodOk = $LASTEXITCODE -eq 0

$manual = @(
  "## 1. Render (backend)",
  "1. Push repo to GitHub",
  "2. https://dashboard.render.com → New → Blueprint → select repo",
  "3. Set secrets: **API_KEY** = ``$ApiKey``, **GROQ_API_KEY** = your Groq key",
  "4. After deploy, URL should match: ``$RenderUrl``",
  "",
  "## 2. GitHub Pages (privacy)",
  "1. Repo → Settings → Pages → Source: **GitHub Actions**",
  "2. Push to main — workflow `.github/workflows/pages.yml` deploys `docs/`",
  "3. Privacy URL: $privacyBase/privacy.html",
  "",
  "## 3. EAS Build",
  "```powershell",
  "npm install -g eas-cli",
  "eas login",
  "eas init",
  "npm run validate:preview",
  "npm run build:preview",
  "```",
  "",
  "## 4. Google Play Console",
  "- Package: **com.matchcv.app**",
  "- Products: monthly, yearly, lifetime (see store/payments.md)",
  "- License testers for sandbox purchases",
  "",
  "## 5. RevenueCat",
  "- Add Google Play app, service account JSON",
  "- Entitlement: **premium**",
  "- Paste goog_ key → re-run release-setup or edit .env",
  "",
  "## 6. Production AAB",
  "```powershell",
  "npm run release:prod",
  "# or: eas submit --platform android",
  "```"
)

$report = @"
# MatchCV — Release Status

Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm")

## Auto-configured
- [x] `.env` — API URL, keys, privacy URLs
- [x] `backend/.env` — matching API_KEY
- Preview validation: $(if ($previewOk) { "PASS" } else { "FAIL — fix placeholders" })
- Production validation: $(if ($prodOk) { "PASS" } else { "FAIL — set Render URL + GitHub user" })

## Your values
| Key | Value |
|-----|-------|
| API_KEY | ``$ApiKey`` |
| EXPO_PUBLIC_API_URL | ``$RenderUrl`` |
| Privacy | ``$privacyBase/privacy.html`` |
| Package | ``com.matchcv.app`` |

## Manual steps

$($manual -join "`n")
"@

$reportPath = Join-Path $root "RELEASE_STATUS.md"
Set-Content -Path $reportPath -Value $report -Encoding UTF8

Write-Host "`nReport: $reportPath" -ForegroundColor Green
Write-Host "`nNext: eas login && eas init && npm run build:preview`n" -ForegroundColor Cyan
