# Release setup wizard - MatchCV
# Usage:
#   .\scripts\release-setup.ps1
#   .\scripts\release-setup.ps1 -RenderUrl "https://matchcv-api.onrender.com" -GitHubUser "milkgifter"

param(
  [string]$RenderUrl = "",
  [string]$GitHubUser = "",
  [string]$ExpoOwner = "",
  [string]$RevenueCatKey = "",
  [string]$ApiKey = "",
  [switch]$NonInteractive
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

function Prompt-Value {
  param(
    [string]$Label,
    [string]$Default = "",
    [switch]$NonInteractive
  )
  if ($NonInteractive) { return $Default }
  $suffix = if ($Default) { " [$Default]" } else { "" }
  $raw = Read-Host "$Label$suffix"
  if ([string]::IsNullOrWhiteSpace($raw)) { return $Default }
  return $raw.Trim()
}

Write-Host ""
Write-Host "=== MatchCV - Release Setup ===" -ForegroundColor Cyan
Write-Host ""

if (-not $RenderUrl) {
  $RenderUrl = Prompt-Value -Label "Backend URL on Render" -Default "https://matchcv-api.onrender.com" -NonInteractive:$NonInteractive
}
if (-not $GitHubUser) {
  $GitHubUser = Prompt-Value -Label "GitHub username for Pages URL" -Default "milkgifter" -NonInteractive:$NonInteractive
}
if (-not $ExpoOwner) {
  $ExpoOwner = Prompt-Value -Label "Expo username EXPO_OWNER" -Default "" -NonInteractive:$NonInteractive
}
if (-not $RevenueCatKey) {
  $RevenueCatKey = Prompt-Value -Label "RevenueCat Android key goog_xxx or leave empty" -Default "" -NonInteractive:$NonInteractive
}
if (-not $ApiKey) {
  $ApiKey = "prod-" + [guid]::NewGuid().ToString("N").Substring(0, 24)
  Write-Host "Generated API_KEY: $ApiKey" -ForegroundColor DarkGray
}

if ($GitHubUser) {
  $privacyBase = "https://$GitHubUser.github.io/matchcv"
} else {
  $privacyBase = "https://YOUR_GITHUB_USERNAME.github.io/matchcv"
}

$groqKey = ""
$backendEnvPath = Join-Path $root "backend\.env"
if (Test-Path $backendEnvPath) {
  foreach ($line in Get-Content $backendEnvPath) {
    if ($line -match "^GROQ_API_KEY=(.+)$") {
      $groqKey = $Matches[1]
      break
    }
  }
}

$dateStamp = Get-Date -Format "yyyy-MM-dd"
$mobileEnv = @(
  "# Production - generated by release-setup.ps1 $dateStamp"
  "EXPO_PUBLIC_API_URL=$RenderUrl"
  "EXPO_PUBLIC_API_KEY=$ApiKey"
  "EXPO_PUBLIC_PRIVACY_URL=$privacyBase/privacy.html"
  "EXPO_PUBLIC_TERMS_URL=$privacyBase/terms.html"
  "EXPO_PUBLIC_REVENUECAT_API_KEY_ANDROID=$RevenueCatKey"
  "EXPO_PUBLIC_REVENUECAT_API_KEY_IOS="
  ""
  "EAS_PROJECT_ID="
  "EXPO_OWNER=$ExpoOwner"
  "EAS_UPDATE_URL="
) -join "`n"

$backendEnv = @(
  "PORT=3001"
  "API_KEY=$ApiKey"
  "AI_PROVIDER=groq"
  "GROQ_API_KEY=$groqKey"
  "AI_MODEL=llama-3.3-70b-versatile"
  "CORS_ORIGIN=*"
  "RATE_LIMIT_MAX=100"
) -join "`n"

Set-Content -Path (Join-Path $root ".env") -Value $mobileEnv -Encoding UTF8
Set-Content -Path $backendEnvPath -Value $backendEnv -Encoding UTF8

Write-Host ""
Write-Host "Updated .env and backend/.env" -ForegroundColor Green

Write-Host ""
Write-Host "Validating preview profile..." -ForegroundColor Yellow
node scripts/validate-production.js --profile preview
$previewOk = $LASTEXITCODE -eq 0

Write-Host "Validating production profile..." -ForegroundColor Yellow
node scripts/validate-production.js --profile production
$prodOk = $LASTEXITCODE -eq 0

$previewStatus = if ($previewOk) { "PASS" } else { "FAIL - fix placeholders" }
$prodStatus = if ($prodOk) { "PASS" } else { "FAIL - set Render URL and GitHub user" }

$manualLines = @(
  "## 1. Render backend"
  "Set API_KEY and GROQ_API_KEY in Render dashboard"
  "API_KEY = $ApiKey"
  "Backend URL = $RenderUrl"
  ""
  "## 2. GitHub Pages"
  "Settings - Pages - Deploy from branch - main - /docs"
  "Privacy URL = $privacyBase/privacy.html"
  ""
  "## 3. EAS Build"
  "npm install -g eas-cli"
  "eas login"
  "eas init"
  "npm run build:preview"
  ""
  "## 4. Google Play"
  "Package com.matchcv.app - see store/payments.md"
  ""
  "## 5. RevenueCat"
  "Entitlement premium - goog_ key in .env"
  ""
  "## 6. Production AAB"
  "npm run release:prod"
)

$reportLines = @(
  "# MatchCV - Release Status"
  ""
  "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
  ""
  "## Auto-configured"
  "- .env updated"
  "- backend/.env updated"
  "- Preview validation: $previewStatus"
  "- Production validation: $prodStatus"
  ""
  "## Your values"
  "- API_KEY: $ApiKey"
  "- EXPO_PUBLIC_API_URL: $RenderUrl"
  "- Privacy: $privacyBase/privacy.html"
  "- Package: com.matchcv.app"
  ""
  "## Manual steps"
  ""
) + $manualLines

$reportPath = Join-Path $root "RELEASE_STATUS.md"
Set-Content -Path $reportPath -Value ($reportLines -join "`n") -Encoding UTF8

Write-Host ""
Write-Host "Report: $reportPath" -ForegroundColor Green
Write-Host ""
Write-Host "Next: eas login, eas init, npm run build:preview" -ForegroundColor Cyan
Write-Host ""
